#!/usr/bin/env bash

USER_ID=$1
echo "Recommendations for user: $USER_ID"
echo ""
curl -H "Content-Type: application/json" -d "
{
    \"user\": \"$USER_ID\"
}" http://localhost:8000/queries.json
echo ""
